<?php

namespace App\Services\Export;

use App\Models\FinancialEvent;
use App\Services\Odoo\OdooCustomerMapper;
use Carbon\Carbon;

/**
 * CSV-04: Exports approved credit note financial events as Odoo account.move
 * (credit note / reversal) import rows.
 *
 * Only exports events with:
 *   - event_type IN ('credit_note', 'claim', 'spoilage_cool_agristock_fault')
 *   - accounting_status = 'export_ready'
 *   - approval_status   = 'approved'
 *
 * Import order: credit notes MUST be imported after invoices so that
 * the original invoice reference resolves in Odoo.
 *
 * Columns follow the Odoo account.move credit note import template.
 */
class CreditNoteCsvExporter
{
    private const APPROVED_EVENT_TYPES = [
        'credit_note',
        'claim',
        'spoilage_cool_agristock_fault',
    ];

    private const DEFAULT_JOURNAL = 'Customer Invoices';

    public function __construct(private readonly OdooCustomerMapper $mapper) {}

    /**
     * @return array{rows: array, skipped: array}
     */
    public function export(
        ?Carbon $from      = null,
        ?Carbon $to        = null,
        ?array  $eventIds  = null
    ): array {
        $query = FinancialEvent::whereIn('event_type', self::APPROVED_EVENT_TYPES)
            ->where('accounting_status', FinancialEvent::STATUS_EXPORT_READY)
            ->where('approval_status',   FinancialEvent::APPROVAL_APPROVED);

        if ($from) {
            $query->where('event_date', '>=', $from->toDateString());
        }
        if ($to) {
            $query->where('event_date', '<=', $to->toDateString());
        }
        if ($eventIds !== null) {
            $query->whereIn('id', $eventIds);
        }

        $events  = $query->get();
        $rows    = [];
        $skipped = [];

        foreach ($events as $event) {
            $row = $this->buildRow($event);

            if ($row === null) {
                $skipped[] = [
                    'financial_event_id' => $event->financial_event_id,
                    'reason'             => 'missing customer_id',
                ];
                continue;
            }

            $rows[] = $row;
        }

        return compact('rows', 'skipped');
    }

    public function headers(): array
    {
        return [
            'id',
            'partner_id/id',
            'move_type',
            'invoice_date',
            'journal_id/name',
            'ref',
            'invoice_line_ids/product_id/name',
            'invoice_line_ids/quantity',
            'invoice_line_ids/price_unit',
            'invoice_line_ids/name',
            'invoice_origin',
            'narration',
        ];
    }

    public function toCsvString(array $rows): string
    {
        $output = fopen('php://temp', 'r+');
        fputcsv($output, $this->headers());

        foreach ($rows as $row) {
            fputcsv($output, array_values($row));
        }

        rewind($output);
        $csv = stream_get_contents($output);
        fclose($output);

        return $csv;
    }

    // -------------------------------------------------------------------------

    private function buildRow(FinancialEvent $event): ?array
    {
        if (! $event->customer_id) {
            return null;
        }

        $productName = match ($event->event_type) {
            'spoilage_cool_agristock_fault' => '[CAG] Spoilage Compensation',
            'claim'                         => '[CAG] Approved Claim Credit',
            default                         => '[CAG] Credit Note',
        };

        $description = $event->notes
            ?? "Credit note for {$event->event_type} — {$event->financial_event_id}";

        // Link to original invoice if the event carries a source_reference
        $invoiceOrigin = $event->source_reference
            ? 'coolagristock.invoice.' . $event->source_reference
            : '';

        return [
            'id'                               => 'coolagristock.creditnote.' . $event->id,
            'partner_id/id'                    => $this->mapper->externalId($event->customer_id),
            'move_type'                        => 'out_refund',
            'invoice_date'                     => $event->event_date->toDateString(),
            'journal_id/name'                  => self::DEFAULT_JOURNAL,
            'ref'                              => $event->financial_event_id,
            'invoice_line_ids/product_id/name' => $productName,
            'invoice_line_ids/quantity'        => 1,
            'invoice_line_ids/price_unit'      => round($event->amount, 2),
            'invoice_line_ids/name'            => $description,
            'invoice_origin'                   => $invoiceOrigin,
            'narration'                        => 'Generated by COOL AGRISTOCK — approved by user ID ' . ($event->approved_by ?? 'N/A'),
        ];
    }
}
