<?php

return [
    'version' => '1.0',
    'currency' => env('ACCOUNTING_CURRENCY', 'XOF'),
    'financial_event_id_prefix' => env('FINANCIAL_EVENT_ID_PREFIX', 'CAG-FE'),

    'status_values' => [
        'draft',
        'export_ready',
        'exported_csv',
        'synced_api',
        'reconciled',
        'failed',
        'reversed',
    ],

    'chart_of_accounts' => [
        'accounts_receivable'       => 'Accounts Receivable',
        'cash'                      => 'Cash',
        'mobile_money'              => 'Mobile Money',
        'bank'                      => 'Bank',
        'storage_revenue'           => 'Storage Revenue',
        'drying_revenue'            => 'Drying Service Revenue',
        'handling_revenue'          => 'Handling Revenue',
        'customer_advances'         => 'Customer Advances',
        'customer_credit_liability' => 'Customer Credit Liability',
        'spoilage_loss'             => 'Spoilage Loss',
        'revenue_adjustment'        => 'Revenue Adjustment',
        'vat_payable'               => 'VAT Payable',
    ],

    // Accounts rejected by Finance — pending replacement account decisions.
    // Event types that depend on these accounts are blocked from Odoo export
    // until Finance confirms alternative accounts and updates this config.
    'rejected_accounts' => [
        'claims_liability'    => 'Rejected by Finance — replacement account not yet confirmed.',
        'compensation_expense'=> 'Rejected by Finance — replacement account not yet confirmed.',
    ],

    // Event types blocked from export because they reference a rejected account.
    // Remove an event type from this list only after Finance confirms the
    // replacement account and the config is updated.
    'export_blocked_event_types' => [
        'claim',
        'spoilage_cool_agristock_fault',
    ],

    'tax_policy' => [
        'default' => 'Apply VAT only where legally applicable and configured in Odoo.',
        'storage_fee' => 'VAT applicability must be mapped by service type and customer type before export.',
        'drying_fee' => 'VAT applicability must be mapped by service type and customer type before export.',
        'handling_fee' => 'VAT applicability must be mapped by service type and customer type before export.',
        'penalty' => 'VAT applicability must be confirmed before penalty billing is exported.',
        'non_financial_events' => 'No VAT because no invoice or accounting entry is created.',
    ],

    'policies' => [
        'revenue_recognition' => [
            'storage_fee' => 'Recognize revenue when the storage service is earned and invoiced.',
            'drying_fee' => 'Recognize revenue when drying service is completed or contractually billable.',
            'handling_fee' => 'Recognize revenue when handling, loading, unloading, sorting, or packaging service is completed.',
        ],
        'claims_compensation' => [
            'customer_fault' => 'Record an operational incident only. No accounting entry is created unless Finance approves a goodwill credit.',
            'cool_agristock_fault' => 'Create compensation expense and claims liability or customer credit only after Operations and Finance approval.',
            'claim' => 'Approved claims must link to the original stock event, invoice, evidence, approval, and maximum approved amount.',
        ],
        'customer_advance' => [
            'recognition' => 'Advance payments are liabilities until applied to an invoice.',
            'application' => 'Apply advances against future invoices during reconciliation.',
            'overpayment' => 'Treat overpayments as customer credit or advance until refunded or applied.',
        ],
        'finance_approval' => [
            'required_for' => [
                'credit_note',
                'refund',
                'spoilage_cool_agristock_fault',
                'claim',
            ],
            'minimum_evidence' => [
                'source event reference',
                'customer reference',
                'amount and currency',
                'approval user',
                'approval timestamp',
                'reason or investigation note',
            ],
        ],
    ],

    'event_types' => [
        'product_deposit' => [
            'label' => 'Product Deposit',
            'source_events' => ['stocks.created', 'inventory_ops.stock_in'],
            'creates_accounting_entry' => false,
            'classification' => ['custody_stock'],
            'accounting_treatment' => 'No accounting entry. Customer retains ownership. Create warehouse receipt and custody record only.',
            'debit' => null,
            'credit' => null,
            'odoo_model' => null,
            'odoo_object' => 'Operational stock receipt / stock record',
            'trigger' => 'Customer product is received into COOL AGRISTOCK custody.',
            'approval_required' => false,
            'validation_rules' => [
                'customer_id is required',
                'stock_id is required',
                'product_id is required',
                'quantity must be greater than zero',
                'warehouse receipt or source reference is required',
                'amount must be zero unless a separate advance payment event exists',
            ],
        ],

        'storage_fee' => [
            'label' => 'Storage Fee',
            'source_events' => ['billings.created', 'stock.storage_fee_calculated'],
            'creates_accounting_entry' => true,
            'classification' => ['revenue', 'receivable'],
            'accounting_treatment' => 'Service revenue and customer receivable.',
            'debit' => 'accounts_receivable',
            'credit' => ['storage_revenue', 'vat_payable'],
            'odoo_model' => 'account.move',
            'odoo_object' => 'Customer Invoice',
            'trigger' => 'Storage charge is calculated from quantity, duration, and storage tariff.',
            'approval_required' => false,
            'validation_rules' => [
                'customer_id is required',
                'stock_id is required',
                'amount must be greater than zero',
                'storage tariff must be resolvable',
                'tax mapping must be configured before export when VAT applies',
            ],
        ],

        'drying_fee' => [
            'label' => 'Drying Fee',
            'source_events' => ['billings.created', 'service.drying_completed'],
            'creates_accounting_entry' => true,
            'classification' => ['revenue', 'receivable'],
            'accounting_treatment' => 'Drying service revenue and customer receivable.',
            'debit' => 'accounts_receivable',
            'credit' => ['drying_revenue', 'vat_payable'],
            'odoo_model' => 'account.move',
            'odoo_object' => 'Customer Invoice',
            'trigger' => 'Drying service is completed or contractually billable.',
            'approval_required' => false,
            'validation_rules' => [
                'customer_id is required',
                'service product mapping is required',
                'amount must be greater than zero',
                'tax mapping must be configured before export when VAT applies',
            ],
        ],

        'handling_fee' => [
            'label' => 'Handling Fee',
            'source_events' => ['billings.created', 'service.handling_completed'],
            'creates_accounting_entry' => true,
            'classification' => ['revenue', 'receivable'],
            'accounting_treatment' => 'Handling service revenue and customer receivable.',
            'debit' => 'accounts_receivable',
            'credit' => ['handling_revenue', 'vat_payable'],
            'odoo_model' => 'account.move',
            'odoo_object' => 'Customer Invoice',
            'trigger' => 'Handling, loading, unloading, sorting, or packaging service is completed.',
            'approval_required' => false,
            'validation_rules' => [
                'customer_id is required',
                'service product mapping is required',
                'amount must be greater than zero',
                'tax mapping must be configured before export when VAT applies',
            ],
        ],

        'advance_payment' => [
            'label' => 'Advance Payment',
            'source_events' => ['payments.created'],
            'creates_accounting_entry' => true,
            'classification' => ['liability', 'cash_receipt'],
            'accounting_treatment' => 'Cash, bank, or mobile money receipt and customer advance liability.',
            'debit' => ['cash', 'mobile_money', 'bank'],
            'credit' => 'customer_advances',
            'odoo_model' => 'account.payment',
            'odoo_object' => 'Payment / Advance Journal',
            'trigger' => 'Payment is received before an invoice exists or before the receivable is due.',
            'approval_required' => false,
            'validation_rules' => [
                'customer_id is required',
                'amount must be greater than zero',
                'payment method or journal is required',
                'transaction reference is required when available',
            ],
        ],

        'payment_received' => [
            'label' => 'Payment Received',
            'source_events' => ['payments.created'],
            'creates_accounting_entry' => true,
            'classification' => ['cash_receipt', 'receivable_settlement'],
            'accounting_treatment' => 'Cash, bank, or mobile money receipt and reduction of receivable.',
            'debit' => ['cash', 'mobile_money', 'bank'],
            'credit' => 'accounts_receivable',
            'odoo_model' => 'account.payment',
            'odoo_object' => 'Customer Payment',
            'trigger' => 'Customer pays against an existing invoice or billing.',
            'approval_required' => false,
            'validation_rules' => [
                'customer_id is required',
                'amount must be greater than zero',
                'billing or invoice reference is required when payment is not an advance',
                'payment method or journal is required',
            ],
        ],

        'withdrawal' => [
            'label' => 'Product Withdrawal',
            'source_events' => ['releases.created', 'inventory_ops.stock_out'],
            'creates_accounting_entry' => false,
            'classification' => ['operational'],
            'accounting_treatment' => 'Operational event. May trigger final invoice if a customer balance exists.',
            'debit' => null,
            'credit' => null,
            'odoo_model' => null,
            'odoo_object' => 'Stock Movement + optional invoice',
            'trigger' => 'Customer withdraws product from custody.',
            'approval_required' => false,
            'validation_rules' => [
                'customer_id is required',
                'stock_id is required',
                'quantity must be greater than zero',
                'check unpaid fees before release',
            ],
        ],

        'spoilage_customer_fault' => [
            'label' => 'Spoilage - Customer Fault',
            'source_events' => ['rottens.created', 'incidents.created'],
            'creates_accounting_entry' => false,
            'classification' => ['operational_incident'],
            'accounting_treatment' => 'Incident record only. No company liability when customer is responsible.',
            'debit' => null,
            'credit' => null,
            'odoo_model' => null,
            'odoo_object' => 'Incident / claim record',
            'trigger' => 'Spoilage investigation assigns responsibility to customer or pre-existing condition.',
            'approval_required' => true,
            'validation_rules' => [
                'incident evidence is required',
                'responsibility decision is required',
                'operations approval is required',
            ],
        ],

        'spoilage_cool_agristock_fault' => [
            'label' => 'Spoilage - COOL AGRISTOCK Fault',
            'source_events' => ['rottens.created', 'incidents.created'],
            'creates_accounting_entry' => true,
            'classification' => ['expense_loss', 'liability', 'customer_credit'],
            'accounting_treatment' => 'Compensation expense or spoilage loss with claims liability or customer credit.',
            'debit' => ['compensation_expense', 'spoilage_loss'],
            'credit' => ['claims_liability', 'customer_credit_liability'],
            'odoo_model' => 'account.move',
            'odoo_object' => 'Journal Entry / Credit Note',
            'trigger' => 'Spoilage investigation assigns responsibility to COOL AGRISTOCK.',
            'approval_required' => true,
            'validation_rules' => [
                'approved investigation is required',
                'customer_id is required',
                'stock_id is required',
                'approved compensation amount must be greater than zero',
                'finance approval is required before export',
            ],
        ],

        'claim' => [
            'label' => 'Claim Approved',
            'source_events' => ['claims.updated'],
            'creates_accounting_entry' => true,
            'classification' => ['customer_credit', 'credit_note', 'liability'],
            'accounting_treatment' => 'Potential customer credit or compensation after approval.',
            'debit' => ['claims_liability', 'compensation_expense'],
            'credit' => ['customer_credit_liability'],
            'odoo_model' => 'account.move',
            'odoo_object' => 'Credit Note',
            'trigger' => 'Claim is approved by Operations and Finance.',
            'approval_required' => true,
            'validation_rules' => [
                'claim_id is required',
                'approval record is required',
                'original stock event or invoice link is required',
                'approved amount must be greater than zero',
            ],
        ],

        'credit_note' => [
            'label' => 'Credit Note',
            'source_events' => ['claims.approved', 'billing.adjusted'],
            'creates_accounting_entry' => true,
            'classification' => ['credit_note', 'receivable_reduction'],
            'accounting_treatment' => 'Reduces customer receivable or creates customer credit.',
            'debit' => ['revenue_adjustment', 'claims_liability'],
            'credit' => 'accounts_receivable',
            'odoo_model' => 'account.move',
            'odoo_object' => 'Credit Note',
            'trigger' => 'Approved claim, spoilage compensation, or billing correction requires a receivable reduction.',
            'approval_required' => true,
            'validation_rules' => [
                'original invoice reference is required when available',
                'customer_id is required',
                'approved amount must be greater than zero',
                'finance approval is required before export',
            ],
        ],

        'refund' => [
            'label' => 'Refund',
            'source_events' => ['refunds.approved'],
            'creates_accounting_entry' => true,
            'classification' => ['refund', 'cash_payment'],
            'accounting_treatment' => 'Cash, bank, or mobile money payment to customer.',
            'debit' => 'customer_credit_liability',
            'credit' => ['cash', 'mobile_money', 'bank'],
            'odoo_model' => 'account.payment',
            'odoo_object' => 'Refund Payment',
            'trigger' => 'Approved customer credit or claim balance is paid back to customer.',
            'approval_required' => true,
            'validation_rules' => [
                'customer_id is required',
                'approved credit balance is required',
                'refund amount must be greater than zero',
                'payment method or journal is required',
                'finance approval is required before export',
            ],
        ],
    ],
];
