<x-app-layout>
@php
    $online=$statuses->where('connectivity','ONLINE')->count();
    $attention=$statuses->whereIn('severity',['WARNING','CRITICAL'])->count();
    $activeBatches=$environments->filter(fn($e)=>$e->activeBatch)->count();
@endphp
<style>
.fleet{--navy:#17243c;--blue:#2f6fed;--green:#20a474;--line:#e8edf4;color:#27364b}.fleet-hero{background:linear-gradient(120deg,#13223d,#203b68 70%,#2765a8);border-radius:18px;color:#fff;padding:24px 26px;box-shadow:0 12px 30px rgba(29,56,101,.17)}.fleet-hero p{color:#ffffffad;max-width:650px}.fleet-stat{background:#ffffff18;border:1px solid #ffffff24;border-radius:13px;min-width:110px;padding:11px 14px}.fleet-stat strong{display:block;font-size:1.35rem}.fleet-stat span{color:#ffffffad;font-size:.72rem}.env-card{background:#fff;border:1px solid var(--line);border-radius:16px;box-shadow:0 5px 18px rgba(30,52,86,.055);height:100%;overflow:hidden;transition:.2s}.env-card:hover{box-shadow:0 12px 28px rgba(30,52,86,.12);transform:translateY(-2px)}.env-head{border-bottom:1px solid var(--line);padding:17px 18px}.env-name{color:var(--navy);font-size:1rem;font-weight:750}.state-pill{align-items:center;background:#eef1f5;border-radius:99px;color:#657184;display:inline-flex;font-size:.69rem;font-weight:800;gap:6px;padding:6px 9px}.state-pill.online{background:#e9f8f2;color:#147a59}.state-pill.warning{background:#fff5df;color:#9b6500}.state-pill.critical{background:#ffebee;color:#a92e43}.dot{background:currentColor;border-radius:50%;height:7px;width:7px}.env-body{padding:18px}.batch-banner{background:#f4f7fb;border-radius:11px;margin-bottom:16px;padding:11px 12px}.batch-banner small{color:#8490a3;display:block}.quick-readings{display:grid;gap:9px;grid-template-columns:repeat(3,1fr)}.quick-reading{background:#f8fafc;border:1px solid #edf1f6;border-radius:10px;padding:12px 8px;text-align:center}.quick-reading strong{color:var(--navy);display:block;font-size:1.12rem}.quick-reading span{color:#8490a3;font-size:.68rem}.env-foot{align-items:center;border-top:1px solid var(--line);display:flex;justify-content:space-between;padding:13px 18px}.empty-sensors{background:#fff;border:1px dashed #cad5e4;border-radius:18px;padding:56px 24px;text-align:center}.empty-icon{align-items:center;background:#edf3ff;border-radius:18px;color:var(--blue);display:flex;font-size:1.6rem;height:68px;justify-content:center;margin:0 auto 18px;width:68px}.setup-steps{display:flex;gap:10px;justify-content:center;margin-top:22px}.setup-step{background:#f8fafc;border-radius:10px;color:#68768b;font-size:.75rem;padding:10px 14px}.setup-step b{color:var(--blue);margin-right:5px}
</style>
<div class="fleet">
 <section class="fleet-hero mb-4"><div class="row align-items-center g-3"><div class="col-lg-7"><div class="text-uppercase small fw-bold mb-2" style="color:#8bb8ff;letter-spacing:.11em">COOL AGRISTOCK</div><h3 class="text-white mb-2">Smart Sensor Management</h3><p class="mb-0">Monitor active processes, environmental conditions and equipment health across every connected site.</p></div><div class="col-lg-5"><div class="d-flex gap-2 justify-content-lg-end flex-wrap"><div class="fleet-stat"><strong>{{$online}} / {{$environments->count()}}</strong><span>Environments online</span></div><div class="fleet-stat"><strong>{{$activeBatches}}</strong><span>Active batches</span></div><div class="fleet-stat"><strong>{{$attention}}</strong><span>Need attention</span></div></div></div></div></section>
 @if($environments->isEmpty())
 <section class="empty-sensors"><div class="empty-icon"><i class="fas fa-microchip"></i></div><h4>No monitored environments yet</h4><p class="text-muted mx-auto" style="max-width:580px">Connect a dryer, cold room or storage environment to begin seeing live operational data. The dashboard will show only useful process readings—no low-level device details.</p>@if(in_array(auth()->user()->group_id,[1,2]))<a href="{{route('storages.index')}}" class="btn btn-primary mt-2"><i class="fas fa-plus me-1"></i> Configure an environment</a><div class="setup-steps flex-wrap"><span class="setup-step"><b>1</b>Add the equipment</span><span class="setup-step"><b>2</b>Assign a sensor device</span><span class="setup-step"><b>3</b>Start a batch</span></div>@endif</section>
 @else
 <div class="row g-4" id="sensor-overview-grid">@foreach($environments as $environment)@php $s=$statuses[$environment->id];$v=$s['telemetry']??[];$batch=$environment->activeBatch; @endphp
 <div class="col-xl-4 col-md-6" data-env-card="{{$environment->id}}"><article class="env-card"><div class="env-head d-flex justify-content-between gap-2"><div><div class="env-name">{{$environment->name}}</div><small class="text-muted"><i class="fas fa-location-dot me-1"></i>{{$environment->location?:($environment->city?->name??'Site not specified')}}</small></div><div class="d-flex flex-column align-items-end gap-1"><span class="state-pill {{$s['connectivity']==='ONLINE'?'online':''}}"><span class="dot"></span>{{$s['connectivity']}}</span>@if($s['severity']!=='NORMAL')<span class="state-pill {{strtolower($s['severity'])}}">{{$s['severity']}}</span>@endif</div></div><div class="env-body"><div class="batch-banner"><small>{{$batch?'Active batch':'Operating status'}}</small><strong>{{$batch?->batch_code??'Idle'}}</strong>@if($batch)<span class="text-muted small"> · {{$batch->product?->name??'No product'}}</span>@endif</div>@if($s['ok'])<div class="quick-readings"><div class="quick-reading"><strong data-field="chamber_temp">{{$v['chamber_temp']['value']??'—'}}°C</strong><span>Chamber temp.</span></div><div class="quick-reading"><strong data-field="chamber_rh">{{$v['chamber_rh']['value']??'—'}}%</strong><span>Chamber RH</span></div><div class="quick-reading"><strong data-field="airflow">{{$v['airflow']['value']??'—'}} m/s</strong><span>Airflow</span></div></div>@else<div class="alert alert-warning small mb-0">{{$s['error']??__('locale.sensor_unavailable')}}</div>@endif</div><div class="env-foot"><small class="text-muted">Updated {{$s['last_update']?->diffForHumans()??'never'}}</small><a href="{{route('sensors.show',$environment->id)}}" class="btn btn-primary btn-sm">Open dashboard <i class="fas fa-arrow-right ms-1"></i></a></div></article></div>
 @endforeach</div>
 @endif
</div>
@push('scripts')
<script>(function(){setInterval(function(){document.querySelectorAll('[data-env-card]').forEach(function(card){fetch('/sensors/'+card.dataset.envCard+'/status').then(r=>r.ok?r.json():null).then(s=>{if(!s)return;[['chamber_temp','°C'],['chamber_rh','%'],['airflow',' m/s']].forEach(([key,unit])=>{var el=card.querySelector('[data-field="'+key+'"]');if(el&&s.telemetry?.[key])el.textContent=s.telemetry[key].value+unit})}).catch(()=>{})})},30000)})();</script>
@endpush
</x-app-layout>
